apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bookstore
  name: jenkins-deployer-role

rules:
  # Deployments & StatefulSets
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Ingress
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Services, ConfigMaps, Secrets, PVCs
  - apiGroups: [""]
    resources:
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Pods
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch